# All available hooks: https://pre-commit.com/hooks.html
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.2
    hooks:
    # any R project
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=mlr_style]
    -   id: lintr
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    #  R package development
    -   id: roxygenize
    -   id: use-tidy-description
    -   id: deps-in-desc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
