# tests if the dataset generated by make_data contains the right features and target variable.
test_make_data = function(df, feature_types, target, missings = FALSE) {
  if (missings) {
    expect_true(anyMissing(df))
  } else {
    expect_false(anyMissing(df))
  }
  expect_true(all(feature_types %in% colnames(df)))
  expect_true(target %in% colnames(df))
  if ("logical" %in% colnames(df)) expect_true(is.logical(df$logical))
  if ("integer" %in% colnames(df)) expect_true(is.integer(df$integer))
  if ("numeric" %in% colnames(df)) expect_true(is.numeric(df$numeric))
  if ("character" %in% colnames(df)) expect_true(is.character(df$character))
  if ("factor" %in% colnames(df)) expect_true(is.factor(df$factor))
  if ("ordered" %in% colnames(df)) expect_true(is.ordered(df$ordered))
  if ("twoclass" %in% colnames(df)) expect_equal(length(unique(df$twoclass)), 2)
  if ("multiclass" %in% colnames(df)) expect_true(length(unique(df$multiclass)) >= 3)
  if ("regr" %in% colnames(df)) expect_true(is.numeric(df$regr))
}

# given the parameters target and missings, all feature type combinations are tested
test_all_combinations = function(feature_types, target, missings) {
  combs = (lapply(1:length(feature_types), combn, x = feature_types, simplify = FALSE)) #get all possible feature type combinations
  #loop over number of feature types
  for (i in 1:length(combs)) {
    combs_i = combs[[i]]
    df_list = lapply(combs_i, function(x) make_data(feature_types = x, target = target, missings))
    mapply(function(X, Y) test_make_data(X, feature_types = Y, target, missings), X = df_list, Y = combs_i)
  }
}
