test_that("simple", {
  mci = msr("ci.holdout", "classif.acc")
  expect_equal(mci$id, "classif.acc")
  expect_measure(mci)
  rr = resample(tsk("iris"), lrn("classif.rpart"), rsmp("holdout"))
  ci = rr$aggregate(mci)
  expect_numeric(ci)
  expect_true(ci["classif.acc.upper"] >= ci["classif.acc.lower"])
  expect_true(ci["classif.acc"] >= ci["classif.acc.lower"])
  expect_true(ci["classif.acc"] <= ci["classif.acc.upper"])

  expect_equal(names(ci), c("classif.acc", "classif.acc.lower", "classif.acc.upper"))
  bmr = benchmark(benchmark_grid(tsks("sonar", "iris"), lrn("classif.rpart"), rsmp("holdout")))
  cis = bmr$aggregate(mci)
  expect_numeric(cis$classif.acc)
  expect_numeric(cis$classif.acc.lower)
  expect_true(all(cis$classif.acc.upper >= cis$classif.acc.lower))
  expect_true(all(cis$classif.acc >= cis$classif.acc.lower))
  expect_true(all(cis$classif.acc <= cis$classif.acc.upper))
  expect_numeric(cis$classif.acc.upper)
})
