context("test_learner")

test_that("make_data", {
  feature_types = c("logical", "integer", "numeric", "character", "factor", "ordered")

  target = "twoclass"
  missings = FALSE
  test_all_combinations(feature_types, target, missings)

  target = "twoclass"
  missings = TRUE
  test_all_combinations(feature_types, target, missings)

  target = "multiclass"
  missings = FALSE
  test_all_combinations(feature_types, target, missings)

  target = "multiclass"
  missings = TRUE
  test_all_combinations(feature_types, target, missings)

  target = "regr"
  missings = FALSE
  test_all_combinations(feature_types, target, missings)

  target = "regr"
  missings = TRUE
  test_all_combinations(feature_types, target, missings)
})

test_that("make_classif_test_tasks", {
  lrn = LearnerClassifRpart$new()
  tasks = make_classif_test_tasks(lrn)
  lapply(unlist(tasks), assert_task)
})

test_that("test_learner", {
  lrn = LearnerClassifRpart$new()
  test_learner(lrn) #this tests the learner on many tasks, generated by all feature type combinations
})
